apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  
  cluster:
    clusterName: Jenkins-X-Cluster   # cluster name from when you created the eks cluster
    environmentGitOwner: IndusVR #GitHub Org
    environmentGitPublic: true #Repos are public
    provider: eks
    region: us-west-2
    devEnvApprovers:
    - todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: nexus
  secretStorage: vault
  vault: 
       aws:
       autoCreate: true
       iamUserName: Indrajit
 disableURLDiscovery: true
  webhook: lighthouse
